"""
ConduitScore E2E test suite — runs against live production at https://conduitscore.com.

Generated by web-app-e2e-tester skill on 2026-04-16.

Priority levels:
  P0 (blocking) — must pass or deploy is broken
  P1 (should)   — user-visible regressions
  P2 (nice)     — polish and SEO
"""

import json
import sys
import time
from datetime import datetime
from pathlib import Path
from playwright.sync_api import sync_playwright, Page, BrowserContext, TimeoutError as PWTimeout

BASE = "https://conduitscore.com"
OUT_DIR = Path(__file__).parent / "output"
OUT_DIR.mkdir(exist_ok=True)
SCREENSHOT_DIR = OUT_DIR / "failures"
SCREENSHOT_DIR.mkdir(exist_ok=True)
TRACE_DIR = OUT_DIR / "traces"
TRACE_DIR.mkdir(exist_ok=True)

MAX_RETRIES = 1
RESULTS = []


def record(name, priority, status, note="", screenshot=None):
    RESULTS.append({
        "test": name,
        "priority": priority,
        "status": status,
        "note": note,
        "screenshot": str(screenshot) if screenshot else None,
        "timestamp": datetime.utcnow().isoformat() + "Z",
    })
    icon = {"PASS": "PASS", "FAIL": "FAIL", "ERROR": "ERR "}[status]
    print(f"  [{icon}] {priority} {name}  {note}")


def collect_console_errors(page: Page):
    errors = []
    page.on("console", lambda msg: errors.append(msg.text) if msg.type == "error" else None)
    page.on("pageerror", lambda exc: errors.append(f"pageerror: {exc}"))
    return errors


def assert_clean_console(errors, test_name):
    # ignore known benign noise
    ignore = ("favicon", "preload", "was preloaded", "manifest.webmanifest",
              "Failed to load resource: net::ERR_NAME_NOT_RESOLVED",
              "sentry", "chrome-extension://", "googletagmanager", "google-analytics",
              "hydration", "Text content did not match", "plausible")
    unexpected = [e for e in errors if not any(k.lower() in e.lower() for k in ignore)]
    return unexpected


def run_with_retry(test_fn, browser, test_name, priority):
    for attempt in range(MAX_RETRIES + 1):
        context = browser.new_context(viewport={"width": 1280, "height": 800})
        if attempt > 0:
            context.tracing.start(screenshots=True, snapshots=True)
        page = context.new_page()
        errors = collect_console_errors(page)
        try:
            test_fn(page, errors)
            if attempt > 0:
                context.tracing.stop(path=str(TRACE_DIR / f"{test_name}_retry.zip"))
            context.close()
            return True
        except Exception as e:
            screenshot = SCREENSHOT_DIR / f"{test_name}_attempt{attempt}.png"
            try:
                page.screenshot(path=str(screenshot), full_page=True)
            except Exception:
                screenshot = None
            if attempt < MAX_RETRIES:
                print(f"  RETRY: {test_name} failed ({e}), retrying...")
                context.close()
                continue
            record(test_name, priority, "FAIL", f"{type(e).__name__}: {str(e)[:200]}", screenshot)
            if attempt > 0:
                try:
                    context.tracing.stop(path=str(TRACE_DIR / f"{test_name}_retry.zip"))
                except Exception:
                    pass
            context.close()
            return False


# ============================================================
# P0 tests — blocking
# ============================================================

def test_homepage_loads(page, errors):
    resp = page.goto(BASE, wait_until="networkidle", timeout=30000)
    assert resp and resp.status < 400, f"homepage returned HTTP {resp.status if resp else 'no response'}"
    assert "ConduitScore" in page.title(), f"unexpected title: {page.title()}"
    unexpected = assert_clean_console(errors, "homepage")
    assert len(unexpected) == 0, f"console errors: {unexpected[:3]}"
    record("P0.homepage_loads", "P0", "PASS", f"title='{page.title()}' status={resp.status}")


def test_privacy_page_has_chrome_extension_section(page, errors):
    resp = page.goto(f"{BASE}/privacy", wait_until="networkidle", timeout=30000)
    assert resp and resp.status < 400, f"/privacy returned HTTP {resp.status}"
    content = page.content()
    assert "2.0 Chrome Extension" in content, "CWS-required 'Chrome Extension' section not found on /privacy"
    assert "chrome.storage.local" in content, "chrome.storage.local retention detail missing"
    assert "domain name" in content.lower(), "extension data description missing"
    record("P0.privacy_chrome_extension_section", "P0", "PASS", "CWS requirement met — deploy is live")


def test_pricing_page_loads(page, errors):
    resp = page.goto(f"{BASE}/pricing", wait_until="networkidle", timeout=30000)
    assert resp and resp.status < 400, f"/pricing returned HTTP {resp.status}"
    content = page.content()
    # pricing mentions $29/$49/$79 from CLAUDE.md
    tier_hits = sum(1 for t in ["$29", "$49", "$79"] if t in content)
    assert tier_hits >= 2, f"pricing tiers missing from page (found {tier_hits}/3)"
    record("P0.pricing_renders", "P0", "PASS", f"{tier_hits}/3 tier prices present")


def test_signin_page_loads(page, errors):
    resp = page.goto(f"{BASE}/signin", wait_until="networkidle", timeout=30000)
    assert resp and resp.status < 400, f"/signin returned HTTP {resp.status}"
    # either a Google button or email magic link input must exist
    has_google = page.locator("button:has-text('Google'), a:has-text('Google')").count() > 0
    has_email = page.locator("input[type='email'], input[name='email']").count() > 0
    assert has_google or has_email, "signin page has neither Google button nor email input"
    record("P0.signin_loads", "P0", "PASS", f"google_btn={has_google} email_input={has_email}")


def test_scan_form_exists_on_homepage(page, errors):
    page.goto(BASE, wait_until="networkidle", timeout=30000)
    # scan form — input + submit button
    inputs = page.locator("input[type='url'], input[type='text'], input[placeholder*='domain' i], input[placeholder*='url' i]")
    assert inputs.count() > 0, "no scan input found on homepage"
    buttons = page.locator("button:has-text('Scan'), button:has-text('Check'), button:has-text('Analyze'), button[type='submit']")
    assert buttons.count() > 0, "no scan submit button on homepage"
    record("P0.scan_form_present", "P0", "PASS", f"inputs={inputs.count()} buttons={buttons.count()}")


def test_api_health(page, errors):
    resp = page.goto(f"{BASE}/api/health", wait_until="load", timeout=15000)
    assert resp, "no response from /api/health"
    assert resp.status < 500, f"/api/health returned {resp.status}"
    record("P0.api_health", "P0", "PASS", f"status={resp.status}")


# ============================================================
# P1 tests — user-visible regressions
# ============================================================

def test_scan_result_invalid_id_graceful(page, errors):
    resp = page.goto(f"{BASE}/scan-result?id=nonexistent-invalid-id-12345", wait_until="networkidle", timeout=30000)
    assert resp and resp.status < 500, f"scan-result blew up with {resp.status}"
    content = page.content()
    # should render SOMETHING, not a raw error page
    assert len(content) > 500, "scan-result page is suspiciously short"
    # should either show "not found" style message or redirect
    record("P1.scan_result_invalid_id_graceful", "P1", "PASS", f"status={resp.status} len={len(content)}")


def test_pricing_cta_links_to_stripe_or_signin(page, errors):
    page.goto(f"{BASE}/pricing", wait_until="networkidle", timeout=30000)
    # find the Pro / Starter / Growth CTAs
    cta = page.locator("button:has-text('Start'), a:has-text('Start'), button:has-text('Upgrade'), a:has-text('Upgrade'), button:has-text('Subscribe'), a:has-text('Subscribe'), button:has-text('Get Started'), a:has-text('Get Started')").first
    assert cta.count() > 0 or page.locator("[href*='signin'], [href*='stripe'], [href*='checkout']").count() > 0, \
        "no subscribe/upgrade CTAs found on pricing page"
    record("P1.pricing_has_ctas", "P1", "PASS", "upgrade/subscribe affordance present")


def test_homepage_mobile_no_horizontal_overflow(page, errors):
    page.set_viewport_size({"width": 375, "height": 812})
    page.goto(BASE, wait_until="networkidle", timeout=30000)
    # compare scroll width to viewport
    scroll_w = page.evaluate("document.documentElement.scrollWidth")
    client_w = page.evaluate("document.documentElement.clientWidth")
    # allow 2px fudge for sub-pixel rounding
    assert scroll_w - client_w <= 2, f"horizontal overflow on homepage mobile: scrollW={scroll_w} clientW={client_w}"
    record("P1.homepage_mobile_no_overflow", "P1", "PASS", f"scrollW={scroll_w} clientW={client_w}")


def test_privacy_mobile_no_horizontal_overflow(page, errors):
    page.set_viewport_size({"width": 375, "height": 812})
    page.goto(f"{BASE}/privacy", wait_until="networkidle", timeout=30000)
    scroll_w = page.evaluate("document.documentElement.scrollWidth")
    client_w = page.evaluate("document.documentElement.clientWidth")
    assert scroll_w - client_w <= 2, f"horizontal overflow on /privacy mobile: scrollW={scroll_w} clientW={client_w}"
    record("P1.privacy_mobile_no_overflow", "P1", "PASS", f"scrollW={scroll_w} clientW={client_w}")


def test_pricing_mobile_no_horizontal_overflow(page, errors):
    page.set_viewport_size({"width": 375, "height": 812})
    page.goto(f"{BASE}/pricing", wait_until="networkidle", timeout=30000)
    scroll_w = page.evaluate("document.documentElement.scrollWidth")
    client_w = page.evaluate("document.documentElement.clientWidth")
    assert scroll_w - client_w <= 2, f"horizontal overflow on /pricing mobile: scrollW={scroll_w} clientW={client_w}"
    record("P1.pricing_mobile_no_overflow", "P1", "PASS", f"scrollW={scroll_w} clientW={client_w}")


def test_robots_txt_served(page, errors):
    resp = page.goto(f"{BASE}/robots.txt", wait_until="load", timeout=15000)
    assert resp and resp.status < 400, f"/robots.txt returned {resp.status}"
    record("P1.robots_txt", "P1", "PASS", f"status={resp.status}")


def test_sitemap_xml_served(page, errors):
    resp = page.goto(f"{BASE}/sitemap.xml", wait_until="load", timeout=15000)
    assert resp and resp.status < 400, f"/sitemap.xml returned {resp.status}"
    record("P1.sitemap_xml", "P1", "PASS", f"status={resp.status}")


def test_homepage_no_404_subresources(page, errors):
    failed = []

    def on_response(resp):
        if resp.status >= 400 and resp.status != 401:  # 401 on auth endpoints is expected
            # ignore third-party tracking that may legit 404
            if any(d in resp.url for d in ("google-analytics", "doubleclick", "facebook", "googletagmanager")):
                return
            failed.append(f"{resp.status} {resp.url}")

    page.on("response", on_response)
    page.goto(BASE, wait_until="networkidle", timeout=30000)
    assert len(failed) == 0, f"{len(failed)} failed subresources: {failed[:3]}"
    record("P1.homepage_no_404_subresources", "P1", "PASS", "all subresources loaded")


# ============================================================
# P2 tests — polish
# ============================================================

def test_homepage_meta_description_present(page, errors):
    page.goto(BASE, wait_until="domcontentloaded", timeout=20000)
    desc = page.locator('meta[name="description"]').get_attribute("content")
    assert desc and len(desc) > 20, f"meta description missing or too short: {desc!r}"
    record("P2.homepage_meta_desc", "P2", "PASS", f"len={len(desc)}")


def test_privacy_page_title_is_descriptive(page, errors):
    page.goto(f"{BASE}/privacy", wait_until="domcontentloaded", timeout=20000)
    title = page.title()
    assert "Privacy" in title, f"/privacy title missing 'Privacy': {title!r}"
    record("P2.privacy_title", "P2", "PASS", f"title='{title}'")


def test_homepage_has_og_image(page, errors):
    page.goto(BASE, wait_until="networkidle", timeout=30000)
    og = page.locator('meta[property="og:image"]').get_attribute("content", timeout=5000)
    assert og and og.startswith("http"), f"og:image missing or relative: {og!r}"
    record("P2.homepage_og_image", "P2", "PASS", f"og:image={og[:60]}")


# ============================================================
# Runner
# ============================================================

TESTS = [
    # P0
    ("homepage_loads", test_homepage_loads, "P0"),
    ("privacy_chrome_extension_section", test_privacy_page_has_chrome_extension_section, "P0"),
    ("pricing_renders", test_pricing_page_loads, "P0"),
    ("signin_loads", test_signin_page_loads, "P0"),
    ("scan_form_present", test_scan_form_exists_on_homepage, "P0"),
    ("api_health", test_api_health, "P0"),
    # P1
    ("scan_result_invalid_id_graceful", test_scan_result_invalid_id_graceful, "P1"),
    ("pricing_has_ctas", test_pricing_cta_links_to_stripe_or_signin, "P1"),
    ("homepage_mobile_no_overflow", test_homepage_mobile_no_horizontal_overflow, "P1"),
    ("privacy_mobile_no_overflow", test_privacy_mobile_no_horizontal_overflow, "P1"),
    ("pricing_mobile_no_overflow", test_pricing_mobile_no_horizontal_overflow, "P1"),
    ("robots_txt", test_robots_txt_served, "P1"),
    ("sitemap_xml", test_sitemap_xml_served, "P1"),
    ("homepage_no_404_subresources", test_homepage_no_404_subresources, "P1"),
    # P2
    ("homepage_meta_desc", test_homepage_meta_description_present, "P2"),
    ("privacy_title", test_privacy_page_title_is_descriptive, "P2"),
    ("homepage_og_image", test_homepage_has_og_image, "P2"),
]


def main():
    start = time.time()
    print(f"Running {len(TESTS)} E2E tests against {BASE}")
    print(f"Output: {OUT_DIR}\n")

    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        for name, fn, priority in TESTS:
            run_with_retry(fn, browser, name, priority)
        browser.close()

    # summarize
    by_prio = {"P0": {"pass": 0, "fail": 0, "total": 0},
               "P1": {"pass": 0, "fail": 0, "total": 0},
               "P2": {"pass": 0, "fail": 0, "total": 0}}
    for r in RESULTS:
        by_prio[r["priority"]]["total"] += 1
        key = "pass" if r["status"] == "PASS" else "fail"
        by_prio[r["priority"]][key] += 1

    def rate(d):
        return f"{d['pass']}/{d['total']}" + ("" if d["total"] == 0 else f" ({100*d['pass']//d['total']}%)")

    summary = {
        "run_at": datetime.utcnow().isoformat() + "Z",
        "base_url": BASE,
        "duration_seconds": round(time.time() - start, 1),
        "total": len(RESULTS),
        "passed": sum(1 for r in RESULTS if r["status"] == "PASS"),
        "failed": sum(1 for r in RESULTS if r["status"] == "FAIL"),
        "checkpoints": {
            "p0_pass_rate": by_prio["P0"]["pass"] / by_prio["P0"]["total"] if by_prio["P0"]["total"] else 0,
            "p1_pass_rate": by_prio["P1"]["pass"] / by_prio["P1"]["total"] if by_prio["P1"]["total"] else 0,
            "p2_pass_rate": by_prio["P2"]["pass"] / by_prio["P2"]["total"] if by_prio["P2"]["total"] else 0,
        },
        "deployment_gate": {
            "p0_blocking": by_prio["P0"]["fail"] > 0,
            "p1_blocking": by_prio["P1"]["fail"] > 0,
        },
        "results": RESULTS,
    }

    (OUT_DIR / "test_report.json").write_text(json.dumps(summary, indent=2))

    print("\n" + "=" * 60)
    print(f"SUMMARY  —  {summary['duration_seconds']}s elapsed")
    print("=" * 60)
    print(f"P0 (blocking)  : {rate(by_prio['P0'])}")
    print(f"P1 (should)    : {rate(by_prio['P1'])}")
    print(f"P2 (polish)    : {rate(by_prio['P2'])}")
    print(f"Total          : {summary['passed']}/{summary['total']}")
    print(f"Report         : {OUT_DIR}/test_report.json")

    # exit code
    if summary["deployment_gate"]["p0_blocking"]:
        print("\nDEPLOY GATE: BLOCKED by P0 failures")
        sys.exit(1)
    if summary["deployment_gate"]["p1_blocking"]:
        print("\nDEPLOY GATE: WARNING — P1 failures (non-blocking but review required)")
        sys.exit(0)
    print("\nDEPLOY GATE: CLEAR")
    sys.exit(0)


if __name__ == "__main__":
    main()
